### ISSUE TITLE
Lone Wanderer Perk[BUG]

### ISSUE THREAD

**Issue by pyronica** [bugthesda/Fallout76-Issue-Tracker#12] opened 2019-02-04 12:28 UTC
**Describe the bug**
Lone Wanderer Perk, is an up to +3 points perk card. However, when I recieved an additional 4th Lone Wanderer Card, I was allowed to combine the 4th perk card to the one with 3 points. Now my card has 4 points allocated to it. This wouldnt be a problem if it benefited me, however, instead now I lost a point ability, so I cannot equip the card spec I wanted to equip, without having to add another point to Charisma.

**Console (please complete the following information or remove if not applicable):**
 - Device: Xbox1 S
 - OS: Latest
 - Game Version: Latest

**To Reproduce**
1. Obtain additional Lone Wander Perk Card, beyond +3 points 
2. Go to Lone Wanderer Perk Cards 
3. Combine +3 Point Card with 4th Lone Wandered Perk Card
4. Note you now have 4 points instead of 3 points

**Expected behavior**
If the card is limited to a specific point value, do not allow duplicates beyond the point value, or do not allow "Combine" ability to perk cards that would make it go beyond its rated perk limit

**Screenshots**
Not at XBox now, but can provide screen shot later if necessary

**Additional context**
Please fix so I do not have to carry an additional point in Charisma, when I am satisfied with the points and cards I wish to use.

**Comment by ghost** [comment] 2019-02-04 16:29
This isn't a bug but intended. **Not all cards points are equal to the card level**. You might just need to either:
1- Invest in one more point in Charimsa
2- Rebuild that card by picking it 2 times the next 2 times you level up.

**Comment by Sinuswutz** [comment] 2019-02-04 16:32
This is not a bug.

The rank 3 card of Lone Wanderer requires 4 points in charisma to equip. Rank 2 requires 3 points. Rank 1 requires 2 points. I am myself not a fan of this but this card IS very powerful.

**Comment by despotak** [comment] 2019-02-05 08:21
As people said, `Lone Wanderer` costs 2 points on rank 1, 3 points on rank 2, and 4 points on rank 3. I'll close this issue as a "bug" but you can reopen it as a "feature request" if you have good reasons to propose why it should be changed.

**Closed as completed by despotak** 2019-02-05 08:21 UTC
Labels: bug
